# Generated by Django 6.0.5 on 2026-05-18 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='medicalhistory',
            name='chronic_conditions',
        ),
        migrations.RemoveField(
            model_name='medicalhistory',
            name='medications',
        ),
        migrations.RemoveField(
            model_name='medicalhistory',
            name='past_surgeries',
        ),
        migrations.AddField(
            model_name='medicalhistory',
            name='additional_notes',
            field=models.TextField(blank=True, verbose_name='Additional notes'),
        ),
        migrations.AddField(
            model_name='medicalhistory',
            name='alcohol',
            field=models.BooleanField(default=False, verbose_name='Alcohol consumption'),
        ),
        migrations.AddField(
            model_name='medicalhistory',
            name='asthma',
            field=models.BooleanField(default=False, verbose_name='Asthma'),
        ),
        migrations.AddField(
            model_name='medicalhistory',
            name='blood_group',
            field=models.CharField(choices=[('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('AB+', 'AB+'), ('AB-', 'AB-'), ('O+', 'O+'), ('O-', 'O-'), ('unknown', 'Inconnu')], default='unknown', max_length=10, verbose_name='Blood type'),
        ),
        migrations.AddField(
            model_name='medicalhistory',
            name='current_medications',
            field=models.TextField(blank=True, help_text='Name, dose, frequency.', verbose_name='Current medications'),
        ),
        migrations.AddField(
            model_name='medicalhistory',
            name='diabetes',
            field=models.BooleanField(default=False, verbose_name='Diabetes'),
        ),
        migrations.AddField(
            model_name='medicalhistory',
            name='epilepsy',
            field=models.BooleanField(default=False, verbose_name='Epilepsy'),
        ),
        migrations.AddField(
            model_name='medicalhistory',
            name='family_history',
            field=models.TextField(blank=True, help_text='Eg : Maternal diabetes, paternal hypertension.', verbose_name='Family history'),
        ),
        migrations.AddField(
            model_name='medicalhistory',
            name='hepatitis_b',
            field=models.BooleanField(default=False, verbose_name='Hepatitis B'),
        ),
        migrations.AddField(
            model_name='medicalhistory',
            name='hiv_positive',
            field=models.BooleanField(default=False, verbose_name='HIV-positive'),
        ),
        migrations.AddField(
            model_name='medicalhistory',
            name='hypertension',
            field=models.BooleanField(default=False, verbose_name='High blood pressure'),
        ),
        migrations.AddField(
            model_name='medicalhistory',
            name='other_chronic',
            field=models.TextField(blank=True, help_text='List any other chronic conditions.', verbose_name='Other chronic conditions'),
        ),
        migrations.AddField(
            model_name='medicalhistory',
            name='previous_surgeries',
            field=models.TextField(blank=True, help_text='Eg : Cesarean section in 2019, appendectomy in 2015.', verbose_name='Previous surgeries'),
        ),
        migrations.AddField(
            model_name='medicalhistory',
            name='sickle_cell_disease',
            field=models.BooleanField(default=False, verbose_name='Sickle cell disease'),
        ),
        migrations.AddField(
            model_name='medicalhistory',
            name='smoking',
            field=models.BooleanField(default=False, verbose_name='Smoking'),
        ),
        migrations.AddField(
            model_name='medicalhistory',
            name='tuberculosis',
            field=models.BooleanField(default=False, verbose_name='Tuberculosis'),
        ),
        migrations.AlterField(
            model_name='medicalhistory',
            name='allergies',
            field=models.TextField(blank=True, help_text='Medications, foods, latex, etc.', verbose_name='Known allergies'),
        ),
    ]
